project:
  type: manuscript

manuscript:
  article: index.qmd

preview-mode: raw

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  pdf: default



exclude:
  - "messy_notes/"

execute:
  freeze: true



